### PR TITLE
Fix null reference and segfault in coinselection.cpp, makeGroup(..)

### LINKED ISSUE #912: gigaperf: makeGroup(..) function in coinselection.cpp broken for gigaperf branch
This is likely for @gandrewstone :

I tried doing a 'sendtoaddress' on my weakblocks stuff on top of my gigaperf branch and got a segfault. I am quite sure that the segfault isn't related to my stuff and after consulting stackoverflow regarding the handling of null-references, I am sure that there's an error in here (in coinselection.cpp, commit aa9510b437 (which curiously is from *2016* but doesn't appear in any of the BU branches?!):
```
TxoGroup makeGroup(SpendableTxos::iterator i, const TxoGroup& prev = *(TxoGroup*)NULL)
{
  TxoGroup ret;
  if (&prev) ret = prev;
```
With the `sendtoadress` RPC call, I get a segfault on the `if (&prev) ...` line. Stackoverflow regarding null references (which I never encountered or thought much about, seemingly for good reason):

https://stackoverflow.com/a/4364586

### PR DESCRIPTION
**Pull request by awemany**
Replace it with a pointer.
Null references are undefined, see e.g. https://stackoverflow.com/a/4364586

Segfault occurred because the assignment 'ret = prev' failed with
prev being a null reference.

Thanks to @griffith for figuring that out.

Closes #912.

### CODE REVIEW

**Comment by Greg-Griffith** [comment]
Just a note after looking at the travis logs... Although the build did fail, the build errors/failures on travis have nothing to do with the code that was edited. Interesting. It seems gigaperf needs some cleanup in general in this regard.

**Comment by sickpig** [comment]
there are different failures here.

one is due to formatting issue on `main.cpp`
https://travis-ci.org/BitcoinUnlimited/BitcoinUnlimited/jobs/328678292#L4384

the others happen on `make check`. 
it fails on a series of tesss, the first one is `policyestimator_tests/BlockPolicyEstimates`
https://travis-ci.org/BitcoinUnlimited/BitcoinUnlimited/jobs/328678292#L4556

finale report said that `241 failures are detected `

File: src/wallet/coinselection.cpp [hunk 1]
```diff
@@ -41,10 +41,10 @@ CAmount reasonableExcess(CAmount targetValue)
 }
 
 // Create a group of Txos from a Txo index and another group.
-TxoGroup makeGroup(SpendableTxos::iterator i, const TxoGroup& prev = *(TxoGroup*)NULL)
+TxoGroup makeGroup(SpendableTxos::iterator i, const TxoGroup* prev = NULL)
 {
   TxoGroup ret;
-  if (&prev) ret = prev;
+  if (prev != NULL) ret = *prev;
   else ret.first = 0;
```
Comment (ptschip) [inline src/wallet/coinselection.cpp]: use C++11 nullptr

Comment (Greg-Griffith) [reply src/wallet/coinselection.cpp]: there really is no difference in this case since the function is setting it to NULL in the default parameter.  

although ptschip does make a good point that using nullptr is probably better in the future over NULL is better because you cant &nullptr, it wont compile. probably better for the project style guide to demand the use of nullptr.

Comment (awemany) [reply src/wallet/coinselection.cpp]: @ptschip : Alright, I changed `NULL` to `nullptr`.

**Comment by gandrewstone** [comment]
@sickpig, this is on our experimental giga_perf branch, which probably doesn't pass all unit tests, etc.  These changes should not have triggered any test failures. We should go thru and fix formatting and unit test failures as a subsequent PR, but for now I'm merging this one because its clearly a problem.

**Comment by sickpig** [comment]
@gandrewstone didn't realize it was against a non standard branch. sorry for the noise.
