### PR TITLE
fix issue where a block's coinbase can make it exceed the configured val

### LINKED ISSUE #258: 1.0.0, block generation can exceed configured configured value depending on coinbase
The block generation in 1.0.0 is only reserving 100 bytes for the coinbase, but this can be exceeded (the reservation only takes into account the coinbase string, not the full tx).  This can cause blocks to exceed 1MB.  

As a workaround, run: ./bitcoin-cli setminingmaxblock 999000

Additionally, miners often take the block generated by getblocktemplate, remove the coinbase, and replace it with their own with a more complex payment.  So the space alloted to the coinbase should be configurable, and default to 1000 to match previous releases.

### PR DESCRIPTION
**Pull request by gandrewstone**
fixes #258

### CODE REVIEW

File: src/test/miner_tests.cpp [hunk 1]
```diff
@@ -187,6 +187,39 @@ BOOST_AUTO_TEST_CASE(CreateNewBlock_validity)
...
+      BOOST_CHECK(pblocktemplate->block.nBlockSize <= maxGeneratedBlock);
+      unsigned int blockSize = pblocktemplate->block.GetSerializeSize(SER_NETWORK, CTransaction::CURRENT_VERSION);
+      BOOST_CHECK(blockSize <= maxGeneratedBlock);
+      //printf("%lu %lu <= %lu\n", (long unsigned int) blockSize, (long unsigned int) pblocktemplate->block.nBlockSize, (long unsigned int) maxGeneratedBlock);
+      delete pblocktemplate;
+    }
+
+    std::string testMinerComment("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLM");
+     // Now generate lots of full size blocks and verify that none exceed the maxGeneratedBlock value
+    //printf("test mining with different sized miner comments");
```
Comment (ptschip) [inline src/test/miner_tests.cpp]: @gandrewstone 
1) I think that by the time you get to running the second loop of tests there will be no more transactions in the pool since they would have been mined out by then, so you'll just be mining empty blocks. (2)  I think you should put a step in there that modifies the miner string "after" the block is created and before we submit the block the way the miners do it...and then we submit the block and check that it was still accepted to and updates the blockchain.

Comment (ptschip) [reply src/test/miner_tests.cpp]: Actually on point number 1 I'm not right, these are just blocktemplates so the txns never get mined.  So that looks fine.

Comment (gandrewstone) [reply src/test/miner_tests.cpp]: I delete the block rather than commit it.  so the transactions are never removed from the mempool.  This saves time since I don't have to make a bunch more transactions for every block size that is tested.

If you uncomment the printfs, you'll see the size of each block when it is created.

Comment (ptschip) [reply src/test/miner_tests.cpp]: ha, i just saw your comment, ignore my previous one...

File: src/miner.cpp [hunk 2]
```diff
@@ -143,7 +143,31 @@ CBlockTemplate* CreateNewBlock(const CChainParams& chainparams, const CScript& s
...
+    // Compute coinbase transaction WITHOUT FEES just to get its size.  We will recompute this at the end when we know the fees.
+    {
+      txNew.vout[0].nValue = 0;  // Will be fixed below, but we need to adjust the size for a possible 9 byte varint
+      txNew.vin[0].scriptSig = CScript() << ((int) 0) << CScriptNum(0);  // block height will be fixed below, but we need to adjust the size for a possible 9 byte varint
+
+      // BU005 add block size settings to the coinbase
+      std::string cbmsg = FormatCoinbaseMessage(BUComments, minerComment);
+      const char* cbcstr = cbmsg.c_str();
+      vector<unsigned char> vec(cbcstr, cbcstr+cbmsg.size());
+      COINBASE_FLAGS = CScript() << vec;
```
Comment (deadalnix) [inline src/miner.cpp:158]: This isn't thread safe. Also, capitalized names by convention are reserved for macros in C/C++ so that's confusing.

**Review by deadalnix — CHANGES_REQUESTED** [review]

**Comment by ptschip** [comment]
i don't see where this is not thread safe...there a lock on cs_main as
well as the memool?

also, capital letter are used throughout bitcoin, there is nothing
unusual or confusing about that IMO.

**Comment by deadalnix** [comment]
> i don't see where this is not thread safe...there a lock on cs_main as well as the memool?

Is it ? It is not taken in the function and there is no assertion that it is taken as precondition.

> also, capital letter are used throughout bitcoin, there is nothing unusual or confusing about that IMO.

Everybody agree that the bitcoin codebase is not the highest quality standard you can find. Conclude.

**Comment by ptschip** [comment]
the locks are taken further up... it's a rather long section of code so
you have to scroll up quite far.

**Comment by ftrader** [comment]
The COINBASE_FLAGS capitalization might be due to it having been some constant earlier on in life. There is a misleading comment about it being constant where it is defined in main.cpp:123 - this should also be fixed as it's not constant now.

`/** Constant stuff for coinbase transactions we create: */`

**Comment by ptschip** [comment]
other than the comment on main.cpp:123 that @ftrader highlighted, this PR looks good to me.

**Comment by gandrewstone** [comment]
ok I'm going to merge with that comment because this is high priority and I'll fix the comment on the "dev" branch.
